### ISSUE TITLE
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.

### ISSUE THREAD

**Issue by dmkuzsib** [daler/gffutils#104]
Hello, 

I try to parse ftp://ftp.solgenomics.net/genomes/Nicotiana_tabacum/sierro_et_al_2014/annotation/Ntab-BX_AWOK-SS_tair10.80-60.gff3

A call to gffutils.create_db ends up with the error:
```
2018-04-26 12:07:35,629 - INFO - Populating features
Traceback (most recent call last):t-order relations: 22000 features

  File "/usr/lib/python3.4/site-packages/gffutils/create.py", line 1288, in create_db
    c.create()
  File "/usr/lib/python3.4/site-packages/gffutils/create.py", line 504, in create
    self._populate_from_lines(self.iterator)
  File "/usr/lib/python3.4/site-packages/gffutils/create.py", line 585, in _populate_from_lines
    self._insert(f, c)
  File "/usr/lib/python3.4/site-packages/gffutils/create.py", line 526, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.

```
The call is as following:
`gffutils.create_db(gfffile, dbfn=gff_db_file, id_spec='ID', merge_strategy='create_unique', force_gff=True, disable_infer_transcripts=True,disable_infer_genes=True,force=True, verbose=True)`

I have also tried other settings for "merge_strategy": "create_unique" or "warning", as well as I tried numerous ways to fiddle other parameters. It always ends up in the same error.

I use the Python 3.4.5, gffutils version 0.9.

Please, help.
Thanks,
Dmitry.

**Comment by daler** [comment]
Hi @dmkuzsib, thanks for reporting. The error is happening on genes that have start coordinates of 0. The GFF and GTF file formats use 1-based coordinates, so this is effectively saying that the gene starts before the chromosome does, and therefore throws off the bin calculation (which can't find a bin and so returns all possible ones, but that's not a single integer as expected hence the error).

Commenting out these problematic genes solves the problem, as well as changing their start position to 1.

However, this brings up more questions about the file: is it just those genes' start positions that are incorrect, or is the whole file off by 1? Are the stop positions similarly shifted? You'll probably have to follow up with the GFF provider to resolve these issues.

If you want to force it just to get something, you can use the [`transform` mechanism](https://daler.github.io/gffutils/database-ids.html#transform) to transform each feature before it makes it into the database, either by incrementing the start only if the start is zero, or incrementing all coordinates by 1, or whatever you decide. For example, the following allows a database to be created from the file you provide:

```python

def f(x):
    "increment every start coordinate"
    x.start += 1
    return x

gffutils.create_db(
    gfffile,
    dbfn=gff_db_file,
    id_spec='ID',
    merge_strategy='create_unique',
    force_gff=True,
    disable_infer_transcripts=True,
    disable_infer_genes=True,
    force=True,
    verbose=True,
    transform=f,
)
```

I will add a more useful error message when a start position of 0 is encountered.

**Comment by dmkuzsib** [comment]
Great, thanks a lot for the solution. 

As I only need these GFF files  to find out the longest isoform, 0- or 1- basis of the coordinate should not change anything. 
While AFAIK majority of gene predication pipelines use 0-based interval, I am not sure actually if GFF standard requires use 0- or 1- based coordinates.

And by the way, thanks a lot for the great software !

Best regards,
Dmitry Kuznetsov,
Swiss Institute of bioinformatics.

**Comment by daler** [comment]
Good, glad to know the solution will work for you!


For future reference, formats differ in 0- vs 1-based, and genome browsers differ in how they handle them . . . 

- https://www.biostars.org/p/84686/
- http://alternateallele.blogspot.de/2012/03/genome-coordinate-cheat-sheet.html

. . . but GFF and GTF standards are pretty explicit about requiring 1-based coords:

- https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md
- http://mblab.wustl.edu/GTF22.html

That said, I wrote gffutils to handle [all sorts of off-spec variants](https://daler.github.io/gffutils/examples.html), and zero-based coords should at least be gracefully handled.
