### ISSUE TITLE
interfeatures - intergenic region with information on flanking genes

### ISSUE THREAD

**Issue by Rhinogradentia** [daler/gffutils#107]
Hi,

I am trying to use interfeatures() on a generator containing genes to fetch all intergenic regions. 
What I would need is the information on the gene ids from the flanking genes of the intergenic region. As the generator doesn't contain the feature id anymore I tried to solve this via pre-filled dictionary. 

```
counter = 0
for g in db.features_of_type('gene'):
            intergenicDict[counter]['gene'] = g
            counter = counter + 1

print(counter)
```

Unfortunately the interfeature-function needs me to merge the db beforehand, otherwise I end up with this error message:
```
  File "/usr/local/lib/python3.6/dist-packages/gffutils/interface.py", line 708, in interfeatures
    assert last_feature.strand == f.strand
AssertionError
```
The merging on the other hand reduces my set somehow from 1634 to only 1604 features. Which makes my set up with the pre-filled dictionary unusable.

```
genes = db.merge(db.features_of_type('gene'),ignore_strand=True)
counter = 0
for IntergenicRegion in db.interfeatures(genes):
            intergenicDict[counter]['start'] = IntergenicRegion.start
            intergenicDict[counter]['stop'] = IntergenicRegion.stop
            counter = counter + 1
print(counter)
```
Honestly I have no idea what the merge function actually merges, because I already reduced my gff to contain only genes (no mRNA, CDS, exon or whatsoever), but I think it has something to do with the strands. 

Is there a better way to accomplish this?

Additonally the merge function seems to have a problem with multiple chromosomes per gff db:

```
  File "/usr/local/lib/python3.6/dist-packages/gffutils/interface.py", line 1042, in merge
    raise NotImplementedError('Merging multiple chromosomes not '
NotImplementedError: Merging multiple chromosomes not implemented
```
I couldn't figure out how I could reduce the generator not only to feature types but also to a certain chromosome.

Any help really appreciated and thank you in advance

Best Regards,
Nadine

**Comment by daler** [comment]
Thanks for reporting. This function was originally written to get introns when only exons exist. In that case, it made sense to ensure strands were the same but when getting intergenic regions, it's overly restrictive. There's also a constraint that the chromosomes must match.

The longer-term solution is to set an inter-feature's strand to be `"."` when the flanking features are on different strands, and to handle multiple chromosomes correctly. I'm assuming you don't want to use `bedtools complement` since there's not a straightforward way of getting flanking genes for each intergenic region.

The current workaround would be the following, where you manually reset the gene strand and only call `interfeatures` on one chromosome at a time:

```python
chroms = [i['seqid'] for i in db.execute('SELECT DISTINCT seqid FROM features;')]

def genes_on_chrom(chrom):
    """
    Yield genes on `chrom`, sorted by start position
    """
    for g in db.features_of_type('gene', order_by='start', limit=(chrom, 0, 1e9))
        g.strand = '.'
        yield g

def intergenic():
    """
    Yield intergenic features
    """
    for chrom in chroms:
        genes = genes_on_chrom(chrom)
        for intergenic in db.interfeatures(genes):
            yield intergenic
```

**Comment by daler** [comment]
Can you see if #108 fixes this issue for you?

**Comment by Rhinogradentia** [comment]
Thank you for your fast answer - I will have a look at #108

**Comment by Rhinogradentia** [comment]
Thank you for the code snippets above - those were really helpful. Even though the result of the intergenic generator now provides always the ID of the first gene on the chromosome and the current gene it is "looking" on. Anyhow this is great and I think I can work with this. 

```
[...]
{'ID': ['PP7435_Chr1-0001', 'PP7435_Chr1-1587'], 'Name': ['PP7435_Chr1-0001', 'PP7435_Chr1-1587'], 'Note': ['PP7435_Chr1-0001', 'PP7435_Chr1-1587'], 'gene': ['FLO100', 'PP7435_Chr1-0001'], 'locus_tag': ['PP7435_Chr1-0001', 'PP7435_Chr1-1587']}
{'ID': ['PP7435_Chr1-0001', 'PP7435_Chr1-1588'], 'Name': ['PP7435_Chr1-0001', 'PP7435_Chr1-1588'], 'Note': ['PP7435_Chr1-0001', 'PP7435_Chr1-1588'], 'gene': ['PP7435_Chr1-0001', 'PP7435_Chr1-1588'], 'locus_tag': ['PP7435_Chr1-0001', 'PP7435_Chr1-1588']}
[...]
```

But I'm afraid the changes in #108 didn't work according the multiple chromosomes and the merge function. (if I got this right).
