### ISSUE TITLE
[performance feature] You should create the DB in memory first, and use prepared SQL statements

### ISSUE THREAD

**Issue by yurivict** [daler/gffutils#109]
File parsing and DB creation takes a very long time. You should create the in-memory DB first, import into it, and then copy it to disk. This speeds up bulk inserts, based on my experience.
 
You should also use prepared SQL statements instead of parsing them every time.

**Comment by yurivict** [comment]
I think that Python use is the core cause of this slowness. The process is CPU-bound, Python is just a wrong language for CPU-intense processes. You need to do CPU-intense operations in C/C++.

**Comment by daler** [comment]
I just tested the human GENCODE annotation (ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz) with:


```python
import gffutils
gffutils.create_db(
  'gencode.v29.annotation.gtf.gz',
  'out.db',
  disable_infer_genes=True,
  disable_infer_transcripts=True,
  verbose=True)
```
and it took 7 mins, which I think is pretty reasonable given all the work gffutils has to do on the 2.7 million features in that file.

Keep in mind that [sqlite does not work on NFS](https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible), in case you're working on a shared filesystem.

Can you provide more specifics on an example that is too slow?

**Comment by yurivict** [comment]
You are right, I can't reproduce it. Not sure what happened last time I tried.

Thanks!

**Comment by endrebak** [comment]
I too am experiencing slowness. I will try to debug; guessing libraries or SQL engine somewhere is at fault:

```
%time db = gffutils.create_db(fn, dbfn='gencode33.db', force=True, keep_order=True, merge_strategy='merge', sort_attribute_values=True)
CPU times: user 7h 49min 59s, sys: 22min 44s, total: 8h 12min 44s
Wall time: 8h 19min 58s
```

I am reading a gencode human gff3 which pandas reads in 80 seconds.

I am trying without order now, but it seems to take about the same time:

```
%time db2 = gffutils.create_db(fn, dbfn='gencode33_fast.db', force=False, keep_order=False, merge_strategy='merge', sort_attribute_values=False)
```

I am on macOS using a gzipped file, but doubt that the latter matters.

**Comment by daler** [comment]
GENCODE includes `transcript_id` and `gene_id` in every line (which is not the GTF spec, but it is convenient). That means you need to use `disable_infer_genes=True, disable_infer_transcripts=True,` to turn off the gene and transcript inference to avoid huge amounts of duplicate work and trying to merge the attributes of all the duplicate entries. Pretty sure that's causing that ridiculously long run time.

https://github.com/daler/gffutils/commit/bd05e0d4eff6e80405c1a862dd62dd42dcf3b393 should be printing a warning, are you getting any warnings?

That said, pandas will always be faster -- it's not doing anything with the attributes field and it's not storing the hierarchy of features and it's not storing anything persistently.

**Comment by endrebak** [comment]
I did not see any warning. I just used the latest gencode GFF3, not the GFF. Perhaps that is why? Will try.
