### ISSUE TITLE
UCSC convention: end_included=false  

### ISSUE THREAD

**Issue by alexpenson** [daler/gffutils#11]
It would be useful to accept GFF files where end-start = length

This can be done in HTSeq:
http://www-huber.embl.de/users/anders/HTSeq/doc/features.html#gff-reader-and-genomicfeature

**Comment by daler** [comment]
Not sure it's worth supporting files that are that far off spec. If anyone has examples of common GTF/GFF providers using these alternative coordinates, please reopen.
