### ISSUE TITLE
Error in specific line(s): sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.

### ISSUE THREAD

**Issue by ieguinoa** [daler/gffutils#112]
Hi, 

I'm having a strange issue when trying to create the db for one of my GFF files.
First of all, the parameters I'm using to create the db are:
merge_strategy="create_unique",force=True,disable_infer_transcripts=True)

And the error is:
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported type.

It's a large gff3 file (wheat annotation) but the error only occurs when I include this feature:
chr5A	IWGSC_March2017	gene	536869655	536871921	51	+	.	ID=TraesCS5A01G326600;primconf=HC

At first I thought it could be just that the start value is too big for the database but this error won't pop up with some other features with larger starting values.
The error still occurs if I change the start value 'slightly', e.g to  536869644. But won't occur with some other values I've tried. e.g 536853129
Only thing I can think of is that this specific start value (and small range around it) can't be represented with the format/resolution of the variable but it would be a great coincidence I guess. 

I'm using gffutils version=0.9 (through conda, installed from bioconda channel)

Cheers,
Ignacio

**Comment by daler** [comment]
Thanks for reporting, can you try #115?

**Comment by ieguinoa** [comment]
It did work indeed, thanks @daler !

**Comment by daler** [comment]
👍

**Comment by BioGeek** [comment]
I can confirm that this fix also works for me on a large gff3 file with wheat annotations.
