### ISSUE TITLE
gffutils.FeatureDB.children missing children for non-exon featuretypes

### ISSUE THREAD

**Issue by lee-van** [daler/gffutils#114]
I am unable to parse all children featuretypes other than 'exon'. I am working with a gencode 29 gff3: `ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.chr_patch_hapl_scaff.annotation.gff3.gz`

`list(DB.children('ENST00000290597.9', featuretype='CDS'))` only returns the first CDS feauture of this particular transcript (there are over 10 exons comprising the CDS):
```[<Feature CDS (chr1:18902462-18902523[-]) at 0x7f83b92004a8>]```

`list(DB.children('ENST00000290597.9', featuretype='exon'))` returns all exons:
```[<Feature exon (chr1:18902462-18902553[-]) at 0x7f83b94f08d0>, <Feature exon (chr1:18877416-18877612[-]) at 0x7f83b94f04e0>, <Feature exon (chr1:18877208-18877255[-]) at 0x7f83b94f0860>, <Feature exon (chr1:18876315-18876467[-]) at 0x7f83b94f0908>, <Feature exon (chr1:18875382-18875503[-]) at 0x7f83b94f02e8>, <Feature exon (chr1:18874463-18874581[-]) at 0x7f83b91e9cc0>, <Feature exon (chr1:18872804-18872957[-]) at 0x7f83b91e9a90>, <Feature exon (chr1:18871430-18871790[-]) at 0x7f83b91e94a8>, <Feature exon (chr1:18890012-18890105[-]) at 0x7f83b91f2e10>, <Feature exon (chr1:18889362-18889454[-]) at 0x7f83b91f2e48>, <Feature exon (chr1:18886464-18886511[-]) at 0x7f83b920c208>, <Feature exon (chr1:18885473-18885628[-]) at 0x7f83b920c278>, <Feature exon (chr1:18883279-18883428[-]) at 0x7f83b920cb38>, <Feature exon (chr1:18883124-18883198[-]) at 0x7f83b920c748>, <Feature exon (chr1:18881700-18881887[-]) at 0x7f83b9214198>, <Feature exon (chr1:18879300-18879373[-]) at 0x7f83b92144e0>]```

**Comment by daler** [comment]
Sorry for not getting to this earlier, but the solution is to use `merge_strategy="create_unique"` when creating the database in the first place. The GENCODE gff does not use unique CDS IDs, and I suspect you used the `merge_strategy="warning"` which ignores all duplicate IDs except for the first one.
