### ISSUE TITLE
Spaces in attributes field prevents create_db from adding parent relationships

### ISSUE THREAD

**Issue by mglubber** [daler/gffutils#128]
I'm trying to import a gff3 file created by GeneMarkS2; 
```
##gff-version3
# extra details
##sequence-region chrom1 1 5675189
chrom1  GeneMark.hmm2   gene    2       235     .       -   .   ID=gene1;
chrom1  GeneMark.hmm2   CDS     2       235     32.67   -   0   ID=1; Parent=gene1; gene_type=native; other_attributes=...;
...
chrom1  GeneMark.hmm2   gene    5706    6470    .       -   .   ID=gene6;
chrom1  GeneMark.hmm2   CDS     5706    6470    32.67   -   0   ID=6; Parent=gene6; gene_type=native; other_attributes=...;
```
Only the first five genes/CDS get a parent/child relation. Additionally, the attributes for the first 5 genes/CDS are created correctly, but all the later ones get a leading white space in the key:
```
print(db["1"].attributes)
ID: ['1']
Parent: ['gene_1']
gene_type: ['native']
other_attributes: [...]

print(db["6"].attributes)
ID: ['6']
 Parent: ['gene_6']
 gene_type: ['native']
 other_attributes: [...]
```
If I remove the whitespace after the `;` separator in the attributes column using `sed -i 's/; /;/g' input.gff3`:
```
##gff-version3
# extra details
##sequence-region chrom1 1 5675189
chrom1  GeneMark.hmm2   gene    2       235     .       -   .   ID=gene1;
chrom1  GeneMark.hmm2   CDS     2       235     32.67   -   0   ID=1;Parent=gene1;gene_type=native;other_attributes=...;
...
chrom1  GeneMark.hmm2   gene    5706    6470    .       -   .   ID=gene6;
chrom1  GeneMark.hmm2   CDS     5706    6470    32.67   -   0   ID=6;Parent=gene6;gene_type=native;other_attributes=...;
```
The relations get created properly for all genes, and all the attribute key are consistent. Since the difference is in the first 10 features (5 genes, 5 CDS), I tried recreating the original file with `checklines=14`, and got correct attributes/relations for the first 7 gene/CDS pairs instead of 5. I'm assuming it's something to do with setting the dialect, and may be related to #51? I can provide the original file if that helps.

**Comment by daler** [comment]
Sorry for the late reply -- yes, providing the original file would help with a solution for this.

**Comment by mglubber** [comment]
First 1000 lines of the file are below, renamed to .txt because github doesn't allow .gff3 extensions. I checked and the issue is occurring in v0.10.1 with this file. 

[gms2_example.txt](https://github.com/daler/gffutils/files/4205281/gms2_example.txt)

**Comment by mglubber** [comment]
And I accidentality closed the issue, sorry

**Comment by cyhollenbeck** [comment]
I'm having the same issue.  Did this, ever get resolved?

**Comment by daler** [comment]
What's happening here is that the first line:

```
k141_73>GeneMark.hmm2>  gene>   3>  365>.>  +>  .>  ID=gene_1;
```

is not representative of more complex lines, and the dialect detection is using the first line it can successfully figure out. One fix could be to manually specify the dialect when creating the db:

```python
...
dialect = {
 'leading semicolon': False,
 'trailing semicolon': True,
 'quoted GFF2 values': False,
 'field separator': ';',
 'keyval separator': '=',
 'multival separator': ',',
 'fmt': 'gff3',
 'repeated keys': False, 
'order': ['ID', 'Parent', 'gene_type', 'partial', 'gc', 'length']
}
```

Another fix could be to manually place a representative line with more complex attributes as the first line in the file.

Neither of these are great options, so I'm trying out probabilistic dialect detection and will keep this open until I make a decision on whether that new functionality will be useful or not.
