### ISSUE TITLE
AttributeError: module 'gffutils' has no attribute 'pybedtools_integration'

### ISSUE THREAD

**Issue by xuanblo** [daler/gffutils#132]
>>> gffutils.pybedtools_integration.to_bedtool(exons)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gffutils' has no attribute 'pybedtools_integration'

**Comment by daler** [comment]
Thanks for reporting. This is intended behavior, because this is an optional module (I don't want to require pybedtools as a dependency to gffutils).

The solution is to import it explicitly, for example:

```python
import gffutils.pybedtools_integration

# or

from gffutils import pybedtools_integration

# or

from gffutils.pybedtools_integration import to_bedtool
```
