### ISSUE TITLE
Repair canonical_transcripts

### ISSUE THREAD

**Issue by EFraim** [daler/gffutils#159]
Canonical transcripts was not functional with newer (>3.5) pythons and newer versions of the class feature (it assumes raw string representation of sequences, which is no longer the case)
I've verified the results against current Ensembl gff database.

Pull request https://github.com/daler/gffutils/pull/156
addresses the issue.
It also apparently breaks 2.x compatibility. Is this of concern to the project?

**Comment by daler** [comment]
Now addressed in v0.11.

**Comment by EFraim** [comment]
Thanks!
