### ISSUE TITLE
Proper way to sort/order features after merge?

### ISSUE THREAD

**Issue by bbimber** [daler/gffutils#161]
I have two GTFs, one NCBI and one Ensembl.  I made two in-memory FeatureDBs using gffutils.create_db().  I would like ot merge them and write our a new GTF with the features in sorted order (accounting for groupings).  

I took these two FeatureDBs and added all the features from one into another, and then iterated sorted features like: 

```
merged = ensdb.update(refdb, disable_infer_transcripts=True, disable_infer_genes=True)
with open('merged.gtf', 'w') as fout:
	for f in merged.all_features(order_by = ('seqid', 'start')):
		fout.write(str(f) + '\n')
```

However, seqid+start doesnt quite get the groupings right.  Is there another way to either merge two sets of features or do a sorting that better matches expected GTF ordering?

Thanks,
Ben

**Comment by daler** [comment]
Sorry for such a late reply, but If this is still an issue can you provide a concrete example I can use to work on a fix?

**Comment by bbimber** [comment]
Thanks for the reply. This is so long ago that I dont think I can make a repro without a lot of work. 

If memory serves, the core issue is that GTF/GFF is a weird format that's not strictly sorted by chr/start/end. Typically the type needs to be included for sorting, except this isnt a standard sort order. I believe I ended up implementing a custom sort function that dealt with the different categories (gene, mrna, exon, etc.).
