### ISSUE TITLE
How to get all chromsome names and  featuretypes

### ISSUE THREAD

**Issue by zhqu1148980644** [daler/gffutils#166]
I know it's possible by using `db.execute` function to make SQL queries, however, this library should be targeted for every bioinformaticians as long as they have basic python knowledges. I mean, it should have some API that looks like `db.chromsomes`, `db.fearuretypes`  to fetch these informations in a native way.

Or if I missed something in the doc.

**Comment by daler** [comment]
Good point, added `db.seqids()` in https://github.com/daler/gffutils/pull/190. Note that `db.featuretypes()` is already available.
