### ISSUE TITLE
`id_spec` default can be misleading

### ISSUE THREAD

**Issue by scimerc** [daler/gffutils#182]
when attempting to use `create_db` without reading the documentation but relying exclusively on the function's docstring, one is induced to believe that `id_spec` defaults to `None`, with ensuing feature type-based auto-increment ID generation fallback strategy.

having a `None` value _actually_ assigned to `id_spec` seems rather difficult since such values are turned into the default (`'ID'` for gff, something else for gtf files).

**Comment by daler** [comment]
Thanks, hopefully this is addressed in https://github.com/daler/gffutils/commit/124cdcd306397c49ade3f0409a33071c5c07e433.

**Comment by daler** [comment]
Now addressed in v0.11.

**Comment by scimerc** [comment]
looks good. just a little typo: "is be".
