### ISSUE TITLE
introns = G.interfeatures(exons) gives 0 introns. is it because exon gives unnamed_exon?

### ISSUE THREAD

**Issue by jekang39** [daler/gffutils#184]
Hello

Thank you very much for developing such useful tools. it is very fast.
I need your help in getting introns.
the following code gave 0 size intron
somehow, the exon had "unnamed_exon" name when I printed out (as shown below)
Is it why it returned 0 size intron?
Is there any other way to get introns either all introns of gff or introns of a gene of interest?

Thank you very much

Best,

JEK

===============================================

exons = G.children(closest_gene_id.id, level=2, featuretype='exon')
         #for i,exon in enumerate(exons):
			    
	        #print("write exon:",i,":",exon.id)
			
iter_length = len(list(exons))
	  		
if iter_length > 1:
  				
  				
	 #introns = list(G.interfeatures(exons))
	 introns=G.interfeatures(exons)
	 iter_intron_length = len(list(introns))

============================================================

**Comment by daler** [comment]
Can you provide a concrete example (with input GFF) so I can help address this?

**Comment by daler** [comment]
@jekang39, please reopen this (and include some example data) if this is still an issue.
