### ISSUE TITLE
Same IDs for gene_id and transcript_id

### ISSUE THREAD

**Issue by andrewprzh** [daler/gffutils#194]
Hi!

First of all - thank you for the awesome lib!

I have a question regarding duplicate ids for a gene and its nested transcript. I read #8, but I'm not sure whether it's the same case.
Here is a part of GTF downloaded here https://ftp.ensembl.org/pub/release-101/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.101.gtf.gz
Both the gene and the transcript have the same id `FBgn0013687`.

```
mitochondrion_genome    FlyBase gene    14917   19524   .       +       .       gene_id "FBgn0013687"; gene_name "mt:ori"; gene_source "FlyBase"; gene_biotype "pseudogene";
mitochondrion_genome    FlyBase transcript      14917   19524   .       +       .       gene_id "FBgn0013687"; transcript_id "FBgn0013687"; gene_name "mt:ori"; gene_source "FlyBase"; gene_biotype "pseudoge
ne"; transcript_source "FlyBase"; transcript_biotype "pseudogene";
mitochondrion_genome    FlyBase exon    14917   19524   .       +       .       gene_id "FBgn0013687"; transcript_id "FBgn0013687"; exon_number "1"; gene_name "mt:ori"; gene_source "FlyBase"; gene_biotype 
"pseudogene"; transcript_source "FlyBase"; transcript_biotype "pseudogene"; exon_id "FBgn0013687-E1";
```

After creating the database the id of the transcript changes (as expected I guess), but its nested exon disappear and remains nested only for a gene, i.e.:

```
db = gffutils.FeatureDB('gene.db')
gene = db["FBgn0013687"] 
for t in db.children(gene):
    print(t.id)               
# FBgn0013687                                                           
# FBgn0013687_1                                                                     
# exon_1 

tr = db["FBgn0013687_1"]
for e in db.children(tr):
    print(e.featuretype, e.id)
# no output
```

GTF and the database are attached [gene.zip](https://github.com/daler/gffutils/files/8843848/gene.zip)

I understand that IDs should be unique in the first place and thus are changed in the database, but it seems that such behavior can be unexpected (transcript record with no exons). Would it make sense to add a warning during the conversion?

Best
Andrey

**Comment by daler** [comment]
Hmm, that's a tricky one. I think in this case it should be considered an error in the GTF itself.

When there are name conflicts during db creation, the merge strategy kicks in. The default behavior is to raise an error. Can you provide the code you used to create the database in the first place?

**Comment by andrewprzh** [comment]
Thank you for the prompt answer, after a quick check I realized `merge_strategy="merge"` is used by default in my tool, so this one is on my side! 

Thank you
Andrey

**Comment by andrewprzh** [comment]
Sorry for bothering again.
I tired used `merge_strategy="error"` and it did raise an error, however using the `merge_strategy='warning'` did not give any message and produced the same database as the one with `merge`:

```
    gffutils.create_db("gene.gtf", "gene.db", force=True, keep_order=True, merge_strategy='warning',
                       sort_attribute_values=True, disable_infer_transcripts=True, disable_infer_genes=True)
```

Andrey
