### ISSUE TITLE
"ValueError: The ID field ID has more than one value" when updating database.

### ISSUE THREAD

**Issue by msarrias** [daler/gffutils#202]
Hi,

I'm trying to update a database with some intron annotations but I'm encountering the following error:

> ValueError: The ID field ID has more than one value but a single value is required for a primary key in the database. Consider using a custom id_spec to convert these multiple values into a single value

These are the steps I followed for creating and updating my db:

```{python}
import gffutils
gff_path = 'GCF_000239415.1.gff'
db_path = 'GCF_000239415.1.db'
my_db = gffutils.create_db(gff_path,
                           dbfn=db_path, 
                           force=True, 
                           keep_order=True,
                           merge_strategy='create_unique',
                           id_spec="ID",
                           sort_attribute_values=True,
                           disable_infer_genes=True,
                           disable_infer_transcripts=True
                           )
introns = list(my_db.create_introns())
my_db.update(introns, 
             force = True, 
             keep_order=True,
             merge_strategy='create_unique',
             id_spec="ID",
             sort_attribute_values=True,
             disable_infer_genes=True,
            disable_infer_transcripts=True
            )
```

The reason why I used `create_unique` as the merging strategy is because of [this issue](https://github.com/daler/gffutils/issues/20). What has me confused is that all annotations in the gff file have an "ID" attribute, which I have specified in the`id_spec` kwarg,. Any advice?

Thanks in advance :) gffutils is a great tool!!

[GCF_000238955.4.gff.zip](https://github.com/daler/gffutils/files/10226929/GCF_000238955.4.gff.zip)

**Comment by daler** [comment]
Yes, looks like this GFF has issues where all CDSs have the same ID, so the `create_unique=True` is required.

Otherwise, I think this looks like #181 -- can you try the solution there, providing an intron-specific ID handler function to the `update()` method?

I'll need to think about how best to handle this in the general case. Maybe automatically detect that there are multiple ID values in the `ID` attribute and instead of just complaining, recommend how to fix it (e.g. with the custom handler).

**Comment by msarrias** [comment]
Hi Ryan,

Thanks a lot for the quick response. The little helper function did the trick. 

Let me know if you come up with a different way to deal with this issue.
