### ISSUE TITLE
gtf_extract command not found with conda installation

### ISSUE THREAD

**Issue by almart7** [daler/gffutils#210]
Hello, I installed gffutils in a conda environment (i've tried versions 0.9 and 0.11) and I am trying to execute the gtf_extract utility but there is a command not found error. I must be missing something obvious here but I cannot find what, could you help me? 

Many thanks.

**Comment by daler** [comment]
Can you clarify what you're aiming to do? There's no gtf_extract utility that I know of in this package.

**Comment by almart7** [comment]
I want to keep specific columns of a GTF and discard some others. I foun
the information here:
https://gffutils.readthedocs.io/en/v0.9.0/GTF_extract.html

**Comment by daler** [comment]
Ah, looks like someone created a package with a similar name, https://github.com/fls-bioinformatics-core/GFFUtils. Looks like that's the package you want.

**Comment by almart7** [comment]
Oh that was confusing haha many thanks!
