### ISSUE TITLE
how to save the modified gff to the disk

### ISSUE THREAD

**Issue by z626093820** [daler/gffutils#217]
Excuse me, how to save the modified gff file to the hard disk？ thanks in advance

**Comment by novigit** [comment]
Once you have done what you wanted to do with your loaded input GFF3 file (here stored in the `db` object), I use this snippet to print the entire db into a logical order

```
# print updated gff record in logical order
for g in db.features_of_type('gene', order_by=('seqid', 'start')):
    print()
    print(g)
    for f in db.children(g, order_by='start'):
        print(f)
```

**Comment by z626093820** [comment]
THANKYOU!!
