### ISSUE TITLE
Update an entry and retain children

### ISSUE THREAD

**Issue by p-polacek** [daler/gffutils#232]
Hi,

I would like to add custom annotations within my database. What I did was take a gene entry, assign new key-value pairs to the "attributes" attribute of the entry, delete the entry from the database and update it with the new entry. This apparently deletes the children (mRNA, exons etc.) of the gene entry. Is there a way to retain the children? Or am I updating the database incorrectly? Thanks!

Peter

**Comment by daler** [comment]
Can you post an example that shows what you're currently doing?

**Comment by p-polacek** [comment]
EDIT: I dug into the scripts and saw that the update() function runs the create() function and handles duplicate IDs based on the strategy specified. I got what I wanted by not deleting the old entry, and specifying merge_strategy="replace".

```python
import gffutils

ann = """1\t.\tgene\t2\t4\t.\t-\t.\tName=P1;ID=P1
1\t.\tmRNA\t2\t4\t.\t-\t.\tID=M1;Parent=P1"""

db = gffutils.create_db(ann, "t.db", from_string=True, force=True)

print(list(db.children("P1"))) # [<Feature mRNA (1:29119-37617[-]) at 0x7fd88379c130>]

new_entry = db["P1"]
new_entry.attributes["X"] = "Y"

db = db.delete([db["P1"]])
db = db.update([new_entry])

print(list(db.children("P1"))) # []
```

Thanks for the quick reply! Here's a minimal example. (sorry for the formatting, I don't know why it doesn't show as code.)

**Comment by daler** [comment]
OK, sounds good. And for posterity I fixed the formatting (see [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for reference)
