### ISSUE TITLE
Dealing with 'hybrid' bedtools gff/bed files?

### ISSUE THREAD

**Issue by yarden** [daler/gffutils#4]
An issue I frequently run into is that bedtools sometimes produces extra fields in its  output, creating files that are strictly not GFF or BED, it seems. For example, if I call `coverageBed` with a BAM input as the `-a` parameter and a GFF as the `-b` parameter, it creates output lines like:

```
chr1    SE  gene    83877956    83908217    .   -   .   ID=chr1:83907290:83908217:-@chr1:83878734:83878799:-@chr1:83877956:83878093:-;Name=chr1:83907290:83908217:-@chr1:83878734:83878799:-@chr1:83877956:83878093:-   18  228 30262   0.0075342
```

where the last four fields are various counts/density values. `gffutils` will not parse this file, yielding:

```
in gffutils.gfffeature.GFFFile.__init__ (gffutils/gfffeature.c:1207)()

ValueError: No features found in file
```

which is technically the correct thing to do, since the file has more than 9 fields and so isn't technically a correct GFF3 file. However, these files are very useful and contain all the information necessary to be treated as if they were GFF3 files.

What do you think is the correct approach to dealing with these files? 

I think it'd be ideal if `bedtools` outputted these values as lower-case optional parameters in the attributes field of the GFF3, since that would preserve the format and allow strict GFF3 parsers to parse the file with no issues, but given that this is not the current format, I'm curious as to how you think these files should be handled in `gffutils`.  Best, --Yarden

**Comment by daler** [comment]
While revisiting old issues, I realized that this has been implemented for >8 yrs now starting in https://github.com/daler/gffutils/commit/49c1c7d11e22003c7da4e7b510092f60970eb1d0.
