### ISSUE TITLE
more flexible FeatureDB.region 

### ISSUE THREAD

**Issue by daler** [daler/gffutils#44]
See comments in #42. It would be useful to select features by entire seqid rather than knowing ahead of time what the seqid size is.

Proposed interface:

```python
# already works
db.region(('chr1', 1, 1000))

# already works
db.region("chr1:1-1000")

# String as first argument? Assume seqid.
db.region('chr1')

# None as "start" position in tuple? 
# Do not add start >= clause (interpret as chr1[:1000]).
db.region(('chr1', None, 1000))

# None as "stop" position in tuple?
# Do not add stop <= clause (interpret as chr1[1000:]
db.region(('chr1', 1000, None))
```

**Comment by rmzelle** [comment]
How about

```
db.region(seqid="chr1", start=1, stop=1000)
```

with "start" and "stop" being optional?

**Comment by daler** [comment]
I should be able to make that work without breaking existing code --  I want to be sure not to break backwards compatibility.

**Comment by daler** [comment]
Please see the [new FeatureDB.region docs](https://pythonhosted.org/gffutils/autodocs/gffutils.FeatureDB.region.html#gffutils.FeatureDB.region) which has examples and a table showing how args/kwargs are interpreted.

**Comment by rmzelle** [comment]
Great, thanks!
