### ISSUE TITLE
Hardcoded temp file does not allow for parallel processes

### ISSUE THREAD

**Issue by schelhorn** [daler/gffutils#47]
There is a [constant for a temp file location in the loader](https://github.com/daler/gffutils/blob/master/gffutils/create.py#L745) that forces multiple parallel versions of gffutils to use the same tempfile. Also, is there any way we can do this without making temp files at all? If `:memory:` is used as the `dbfn` database location, users probably expect gffutils to work without disk access, so a pure in-memory solution would be beneficial in these cases.

**Comment by daler** [comment]
Yikes, thanks for reporting this.  Of course the quick fix is to delete that line and use the more robust tempfile.NamedTemporaryFile in the line above.

Looks like this slipped in during 9360e90d.

I will add some additional machinery for regression testing and for testing multiple parallel versions. Once that's ready I'll release a new version and upload to PyPI.

**Comment by schelhorn** [comment]
Thanks a bunch! A quick commit would be appreciated since the error probably can result in dropped annotations, without the user noticing it.

**Comment by daler** [comment]
OK, pushed the quick fix; currently working on parallel tests.

**Comment by schelhorn** [comment]
Thanks!
