### ISSUE TITLE
Database creation leaves file lock on GFF file?

### ISSUE THREAD

**Issue by rmzelle** [daler/gffutils#49]
Windows won't allow me to delete certain GFF files, and it seems to be a result of `gffutils.create_db`. Using `psutil` to keep track of open files (per http://stackoverflow.com/a/25069136/1712389), I get:

Code:

```
    proc = psutil.Process()
    print ('beforeDB: ' + str(proc.open_files()))

    #create database for genome
    db = gffutils.create_db(genomeGFF, dbfn=genomeGFFdb, force=True, merge_strategy="merge", keep_order=True)

    print ('afterDB: ' + str(proc.open_files()))
```

Output:

```
beforeDB: [popenfile(path=u'C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1)]
afterDB: [popenfile(path=u'C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1), popenfile(path=u'C:\\...\\modify-reference-genome\\temp\\SacceM3707_1_AssemblyScaffolds.gff', fd=-1)]
```

("genomeGFF" matches the "SacceM3707_1_AssemblyScaffolds.gff" file path). Is this a bug? If not, is there a way to release the GFF file? I'm using gffutils 0.8.3.1.

**Comment by daler** [comment]
Huh. I'm seeing the same thing on Linux. Nothing immediately obvious; I'll look into it.

**Comment by rmzelle** [comment]
@daler, I just upgraded from gffutils 0.8.3.1 to 0.8.6.1, and the error is gone, so feel free to close this.

(http://daler.github.io/gffutils/changelog.html is a little out of date, by the way, since it only covers up to 0.8.4)

**Comment by rmzelle** [comment]
And thanks for the fix, of course!!

**Comment by daler** [comment]
Good to hear!  And thanks, I updated the online docs.

I had originally fixed the problem in the `iterators` dev branch, but I don't think I ever merged it into master. So I'll leave this open for now, at least until I have more time to work out what fixed the issue and to add regression tests.

**Comment by rmzelle** [comment]
Ah, yes, you're right. FWIW, the file lock issue isn't always a 100% reproducible for me. In my most recent test, with 0.8.3.1, the first run of my script didn't leave a lock, while the second and third runs did. With 0.8.6.1, three consecutive runs all completed without leaving a file lock. Maybe a race condition, or some variables that don't get properly reinitialized?

**Comment by daler** [comment]
Closing for now; please reopen if you have a reproducible example.
