### ISSUE TITLE
Feature.sequence(): option to extract flanking region

### ISSUE THREAD

**Issue by rimjhimroy** [daler/gffutils#50]
It would be really great to add an option to extract flanking sequence along with the feature sequence using Feature.sequence method.

For instance I want to extract x number of bases flanking then:

`Feature.sequence(fasta, use_strand=True, flanking=x)`

will generate the sequence of:
x(bases)+feature+x(bases)

and argument `flanking=0` will give just the feature sequence (could be set to default).

**Comment by daler** [comment]
I think the best solution for this, and any other sort of interval operations, is to use [pybedtools](https://github.com/daler/pybedtools). You'll have more options and better performance this way.

Key to this is the `gffutils.helpers.asinterval()` function, which will convert a `gffutils.Feature` to a `pybedtools.Interval`. The idiom is to create a generator of intervals, and create a `pybedtools.BedTool` out of it. Then you can use all of pybedtools/BEDTools to manipulate intervals and extract sequences. For example:

```python
from gffutils.helper import asinterval
from gffutils import FeatureDB
import pybedtools

db = FeatureDB('my.db')

def features(chrom):
    "generator function that yields all genes in the database on the provided chrom"
    for gene in db.features_of_type('gene'):
        if gene.chrom != chrom':
            continue
        yield asinterval(gene)

x = pybedtools.BedTool(features("chr1")).saveas('genes.gtf')

# now operate on x, and extract sequences when you're done...
# e.g., gene sequence plus 1kb upstream
extended_genes = x.flank(s=True, l=1000)
extended_genes.sequence(fi="genome.fa", fo="output.fa", s=True)
```
