### ISSUE TITLE
Parser fails on Alias value with spaces

### ISSUE THREAD

**Issue by rmzelle** [daler/gffutils#51]
I am getting the error

```
  File "C:\...\python-2.7.9.amd64\lib\site-packages\gffutils\parser.py", line 164, in _split_keyvals
    assert len(item) == 1, item
AssertionError: [u'Alias=CCHL,cytochrome', u'c', u'heme', u'lyase']
```

for the line

```
scaffold_84	liftOver	CDS	41166	41975	.	-	.	ID=YAL039C_JAY291;Name=YAL039C;orf_classification=Verified;gene=CYC3;Alias=CCHL,cytochrome c heme lyase;dbxref=SGD:S000000037;Note=Cytochrome%20c%20heme%20lyase%20%28holocytochrome%20c%20synthase%29%2C%20attaches%20heme%20to%20apo-cytochrome%20c%20%28Cyc1p%20or%20Cyc7p%29%20in%20the%20mitochondrial%20intermembrane%20space%3B%20human%20ortholog%20may%20have%20a%20role%20in%20microphthalmia%20with%20linear%20skin%20defects%20%28MLS%29
```

According to http://www.sequenceontology.org/gff3.shtml, spaces are allowed in the Alias field ("Note that unescaped spaces are allowed within fields, meaning that parsers must split on tabs, not spaces."), as are multiple values ("In addition to Parent, the Alias, Note, Dbxref and Ontology_term attributes can have multiple values.").

**Comment by daler** [comment]
Thanks for reporting this. I think the dialect inference will need another field to track cases like this and the parser will need some logic rearrangement to handle it.

**Comment by daler** [comment]
Hmm. Using this feature alone, it's parsed fine. Specifically, using:

```python
feature = gffutils.feature.feature_from_line("scaffold_84	liftOver	CDS	41166	41975	.	-	.	ID=YAL039C_JAY291;Name=YAL039C;orf_classification=Verified;gene=CYC3;Alias=CCHL,cytochrome c heme lyase;dbxref=SGD:S000000037;Note=Cytochrome%20c%20heme%20lyase%20%28holocytochrome%20c%20synthase%29%2C%20attaches%20heme%20to%20apo-cytochrome%20c%20%28Cyc1p%20or%20Cyc7p%29%20in%20the%20mitochondrial%20intermembrane%20space%3B%20human%20ortholog%20may%20have%20a%20role%20in%20microphthalmia%20with%20linear%20skin%20defects%20%28MLS%29")
print(feature.attributes)
```

I get

```python
Note: ['Cytochrome%20c%20heme%20lyase%20%28holocytochrome%20c%20synthase%29%2C%20attaches%20heme%20to%20apo-cytochrome%20c%20%28Cyc1p%20or%20Cyc7p%29%20in%20the%20mitochondrial%20intermembrane%20space%3B%20human%20ortholog%20may%20have%20a%20role%20in%20microphthalmia%20with%20linear%20skin%20defects%20%28MLS%29']
dbxref: ['SGD:S000000037']
Name: ['YAL039C']
orf_classification: ['Verified']
Alias: ['CCHL', 'cytochrome c heme lyase']
gene: ['CYC3']
ID: ['YAL039C_JAY291']
```

So there must be some other features earlier in the file (the first 10 probably, unless you change the `checklines` kwarg) that are responsible for inferring a dialect that's not consistent for the rest of the file.

Are you able to supply the entire file? Or a subset that reproduces the problem?

**Comment by rmzelle** [comment]
I'm sorry. I fixed up the original GFF file (I'm pretty sure escaping all spaces with `%20` did the trick), and I'm having trouble recreating the problematic file. Feel free to close for now until I can reproduce.

**Comment by daler** [comment]
Ok -- please reopen if you figure out where the issue was coming from.
