### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by teshomem** [daler/gffutils#67]
I wanted to integrate gffutils database with my existing database (MySQL) for a different purpose. I just need to include the tables to my database and use gffutils attributes in my python codes. Is it possible for you to add MySQL support for this?

Thanks.

**Comment by daler** [comment]
The solution to this would be to use an ORM like `sqlalchemy` which can handle different database backends. I had benchmarked this a while ago and found that it wasn't worth the performance hit for the relatively simple database interactions performed by `gffutils`. So I don't plan on adding mysql support directly.

After briefly looking up conversions of sqlite dumps to mysql, it seems like it's a dataset-dependent process. So I'd be happy to accept pull requests along the lines of a gffutils-specific, sqlite-to-mysql converter. If you get something mostly working, let me know and I can work it into a utilities module in gffutils.

**Comment by teshomem** [comment]
Thanks. I will what I can do.
