### ISSUE TITLE
Control order of attributes

### ISSUE THREAD

**Issue by rmzelle** [daler/gffutils#69]
Is it already possible to control the order of attributes? I'm looking for a way to specify an order that is independent of the attribute order in the original GFF file used to create the database.

E.g. if I want to make sure that the "ID" attribute always precedes the "Name" attribute when printing GFF features to strings, is there a way to do that?

**Comment by daler** [comment]
```python
import gffutils

# get a feature to play with from a db
db = gffutils.create_db(gffutils.example_filename('FBgn0031208.gff'), ':memory:')
f = db.all_features().next()

# the currently configured order
print(f.dialect['order'])

# default prints unordered attributes
print(f)

# When the feature prints, force the order specified in dialect
f.keep_order = True
print(f)

# Try reversing the order; with keep_order=True the string will use the new order
f.dialect['order'] = f.dialect['order'][::-1]
print(f)
```

**Comment by rmzelle** [comment]
Thanks, will give that a try.

**Comment by rmzelle** [comment]
For posterity, I managed to achieve the same by directly changing the dialect on the database, instead of on the individual features. In short:

```
db = gffutils.create_db(genomeGFF, dbfn=genomeGFFdb, force=True, merge_strategy="merge", keep_order=True)
desired_attribute_order = ['ID', 'Name', 'standard_gene_name', 'systematic_gene_name']
db.dialect['order'] = desired_attribute_order 
```
