### ISSUE TITLE
How do I most easily get the gene ID of a transcript when iterating over transcripts?

### ISSUE THREAD

**Issue by endrebak** [daler/gffutils#70]
Here is a solution, in case anyone is wondering how to do it:

```python
def tss_generator(db):
    """Creates bed of TSS regions from gff3 file.

    Also replaces empty score field with gene name."""

    gene_id_re = re.compile("gene_id\":\[\"(.*?)\"\]")

    for transcript in db.features_of_type("transcript"):
        gene_id = re.search(gene_id_re, transcript.astuple()[9]).group(1)
        record = gff2bed(TSS(asinterval(transcript), upstream=1, downstream=0))
        record.score = gene_id
        yield(record)


rule make_tss_bed:
    input:
        infile = "data/gencode_annotation/gencode24.db"
    output:
        outfile = "data/gencode_annotation/tss.bed"
    run:
        db = gffutils.FeatureDB(input.infile)

        tsses = pybedtools.BedTool(tss_generator(db)).slop(b=5000, genome="hg38").saveas(output.outfile)
```

As you can see, I get the gene from a transcript by using `gene_id = re.search(gene_id_re, transcript.astuple()[9]).group(1)`. Is there an attribute/way to get gene id from a transcript I have overlooked?

Thanks for the package btw.

**Comment by daler** [comment]
The following will also catch corner cases where one transcript has multiple gene parents. It's strange, but sometimes it happens:

```python
for transcript in db.features_of_type('transcript'):
    gene_id = list(db.parents(transcript))
```
or
```python
for transcript in db.features_of_type('transcript'):
    gene_id = transcript.attributes['gene_id']
```

But it sounds like you are making something like the `gffutils.pybedtools_integration.tsses()` function, which also handles cases where a gene has multiple transcripts with the same start position to avoid double-counting in downstream analysis. Give that a shot and let me know if it's missing anything.

**Comment by endrebak** [comment]
Thanks.
