### ISSUE TITLE
Append GFF file to an existing db.

### ISSUE THREAD

**Issue by arnikz** [daler/gffutils#72]
Hi,

How can I append features from a new GFF file to an existing db?
```
import gffutils as gff
db_file = 'all.sqlite'
fname1 = 'first.gff'
fname2 = 'second.gff'
db = gff.create_db(fname1, db_file)
#new_db = gff.create_db(fname2, db_file, append=True)???
```
Thanks.

**Comment by daler** [comment]
Sure, give the [`FeatureDB.update()`](http://daler.github.io/gffutils/autodocs/gffutils.interface.FeatureDB.update.html#gffutils.interface.FeatureDB.update) method a try.

**Comment by arnikz** [comment]
@daler Thanks, I've missed it while reading the doc:)
