### ISSUE TITLE
Guarantee referential integrity of the generated SQLite db.

### ISSUE THREAD

**Issue by arnikz** [daler/gffutils#73]
Add FKs to _relations_ table to reference _features_ table and use SQLite pragma to turn on/off the foreign key constraints.

**Comment by daler** [comment]
Yep, that's a good idea. When I first started writing gffutils there were still a lot of sqlite versions < 3.6.19 floating around. I think nowadays it's safe to assume a sqlite version less than 7 yrs old!

**Comment by daler** [comment]
Also: pull requests very welcome. I likely won't have time to work on this for a while.

**Comment by daler** [comment]
Closing; see #74 for discussion.
