### ISSUE TITLE
Add attribute to all exons/CDS in gff3 file

### ISSUE THREAD

**Issue by cbostwick87** [daler/gffutils#75]
Hello. I apologize in advance for my novice question, but I think at this point it is better to ask than to continue to fumble around on my own.  I am trying to add an attribute to all of the exon and/or CDS lines in my gff3 file. I would like to add the "Name" attribute from each Parent gene or mRNA feature to each of its children exons/CDS. A similar issue is mentioned in the introduction of the gffutils documentation (adding a gene_id attribute to exons), but I cannot seem to figure out how to do this simple task. I would greatly appreciate any assistance with this issue. I hope this is the right place to submit such a request, and apologize if it is not. Thank you very much.

Best regards,
Caleb Bostwick

**Comment by daler** [comment]
Sure, can you provide an example input file and an example of the output you're trying to get?

**Comment by cbostwick87** [comment]
Thanks for the fast reply Ryan. I would like the .mod file to end up like the .result file, by adding the Name attribute from the mRNA line to the child CDS attribute line. I would like to do this for ALL the genes in the entire gff3 file, not just the one gene I included in these example files. Thank you very much.
[Obimaculoides_280.mod.gff3.txt](https://github.com/daler/gffutils/files/364508/Obimaculoides_280.mod.gff3.txt)
[Obimaculoides_280.result.gff3.txt](https://github.com/daler/gffutils/files/364509/Obimaculoides_280.result.gff3.txt)

**Comment by daler** [comment]
```python
import gffutils
db = gffutils.create_db('Obimaculoides_280.mod.gff3.txt', ':memory:')

with open('tmp.gff', 'w') as fout:
    for d in db.directives:
        fout.write('##{0}\n'.format(d))

    for feature in db.all_features():
        if feature.featuretype == 'CDS':

            # If level=1 not specified, it will also return gene "grandparent"
            # which you don't care about
            parent = list(db.parents(feature, level=1))

            # sanity checking
            assert len(parent) == 1
            parent = parent[0]

            feature.attributes['Name'] = parent.attributes['Name']
        fout.write(str(feature) + '\n')
```
The order of the attributes differs, even with `create_db(keep_order=True)`, because the original input file doesn't have consistent attribute order itself (the mRNA has pacid before Parent). But as long as you're OK with that, this should work.

**Comment by cbostwick87** [comment]
That worked perfectly. Thanks for taking the time to help me Ryan. Have a nice day.
