### ISSUE TITLE
ValueError triggered by non-standard GFF lines with missing start/end coordinates

### ISSUE THREAD

**Issue by arnikz** [daler/gffutils#85]
Hi,

One of my GFF files contains some (pathological) lines with a missing (empty '') start or end value. Unfortunately, the originators of the files haven't considered to use the dot '.' and, as a result, _gffutils_ raises the following error:

<pre>  
  File "../lib/python2.7/site-packages/gffutils/create.py", line 1241, in create_db
    iterator = iterators.DataIterator(**kwargs)
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 270, in DataIterator
    return _FileIterator(**_kwargs)
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 92, in __init__
    self.peek, self._iter = peek(self._custom_iter(), checklines)
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 30, in peek
    _peek.append(six.next(it))
  File "../lib/python2.7/site-packages/gffutils/iterators.py", line 144, in _custom_iter
    yield feature_from_line(line, dialect=self.dialect)
  File "../lib/python2.7/site-packages/gffutils/feature.py", line 399, in feature_from_line
    return Feature(dialect=dialect, **d)
  File "../lib/python2.7/site-packages/gffutils/feature.py", line 120, in __init__
    start = int(start)
ValueError: invalid literal for int() with base 10: ''
</pre>

Could you consider to handle/log these cases? Thank you.

**Comment by daler** [comment]
Can you give some examples I can use for testing?

**Comment by arnikz** [comment]
@daler: [Here](http://www.animalgenome.org/tmp/qdwnld2651EATM.txt.gz) is one example you could use.

**Comment by daler** [comment]
Thanks. 

Side note: I'm not sure what your bigger-picture goal is, but looking though this particular file there aren't any parent-child relationships (which is what gffutils is most useful for). If you're just doing interval stuff, you might want to consider pybedtools. If you're just trying to get a database of features keyed by QTL_ID, a custom approach might be a lot faster.

**Comment by arnikz** [comment]
My goal is to get the stuff into a database. Custom approaches might be faster but I don't care much about the performance right now and _gffutils_ is not particularly slow;)

**Comment by daler** [comment]
@arnikz I was about to take a look at this (finally) but the link to your example is down. If this is still an issue, can you re-upload?

**Comment by arnikz** [comment]
@daler: Sorry, I provided a temp link based on a session:) Please follow the link to the GFF [here](http://www.animalgenome.org/cgi-bin/QTLdb/SS/download?file=gbpSS_10.2). Thanks

**Comment by arnikz** [comment]
Hi @daler. Did you have a chance to look at the file above?

**Comment by daler** [comment]
@arnikz this dropped off my radar, sorry about that. I will take a look today.

**Comment by arnikz** [comment]
Thanks.
