### ISSUE TITLE
Should I use gffwriter?

### ISSUE THREAD

**Issue by elenimijalis** [daler/gffutils#88]
I'm sorry if I missed this in the docs, but what is the current accepted way to output a new gff file after you have created and manipulated the db from the old gff file? I see a script called "gffwriter.py", but I don't see anything in the docs. Please let me know if I am missing something.

**Comment by daler** [comment]
I really need to either update that or remove it! See this answer https://github.com/daler/gffutils/issues/37#issuecomment-52925428 for details. The "canonical" way to output a new file is to convert whatever features you want to string, and write them to a file:


```python
with open('out.gff', 'w') as fout:
    for feature in db.all_features():
        fout.write(str(feature) + '\n'))

```

**Comment by elenimijalis** [comment]
Thanks so much for the quick reply-- However, what about the file header? For example, using the gff3writer from bcbio-gff, I also get something like this at the beginning of the file:
`##gff-version 3
##sequence-region Miro 1 176055`

**Comment by daler** [comment]
Good point, that's a reason to have a gffwriter class. Currently to get the directives in the output file, you need to write them out separately:

```python
with open('out.gff', 'w') as fout:
    for d in db.directives:
        fout.write('## {0}\n'.format(d))
    for feature in db.all_features():
        fout.write(str(feature) + '\n')
```

**Comment by mictadlo** [comment]
Hi, I added `Note=Gene description` but I failed to write it to a new GFF3 file. This question I posted [here](https://bioinformatics.stackexchange.com/questions/9289/modifing-a-gff3-file-and-writting-to-a-new-file).

How is it possible to fix it?

Thank you in advance,

Michal
