### ISSUE TITLE
Slow performance of  'region' and 'children' methods

### ISSUE THREAD

**Issue by pommy1** [daler/gffutils#92]
Hi Daler,
First of all thanks for gffutils – crucial thing for every genomics biologist using Python : - ))

I've been recently running some scripts. The performance of them is quite slow and I think there some simple changes to sqlite queries which can speed things up dramatically.
1. region method actually make a query on seqid, start, end. So I manually created multicolumn index (seqid, start, end) on table features. After that everything has become 10x or may be even more quicker. Maybe this index can be added on the initial DB creation since it is so important for region method?
2. children method with featuretype keyword runs slow. When I tried the actual query which happens behind the scenes and made EXPLAIN QUERY PLAN on it it returns
0|0|0|SEARCH TABLE features USING INDEX featuretype (featuretype=?)
0|1|1|SEARCH TABLE relations USING COVERING INDEX sqlite_autoindex_relations_1 (parent=? AND child=?)
The thing is that there are a lot of features of certain type (which you indicate as a featuretype keyword) and then this whole bunch (in case of exon almost the whole table) is intersected with what relations table return. If this is done vice verse i.e. first the relation table is searched and then the featuretype is checked then the performance is orders of magnitude faster.

All the best,
Mikhail

**Comment by daler** [comment]
@pommy1 thanks so much for this. I've been meaning to have a benchmarking suite to be able to test these sorts of tweaks.

1) I suspect the `region` part of gffutils isn't used much because BEDTools/pybedtools is so much better at this sort of thing, and maybe that's why it hasn't been reported as being slow. But anyone using `region` will benefit from the extra index and the only cost I see is in file size bloat. I think it's reasonable to add it as a default index.

2) I've never used EXPLAIN QUERY PLAN, but apparently I should have. It's not immediately clear to me how the query should be modified. Would this be as simple as rearranging the blocks in `helpers.make_query`? Or, to put it another way, can you paste the faster children-with-featuretype query?

**Comment by pommy1** [comment]
1. Cool!
2. Currently the query looks something like this. 
`SELECT DISTINCT id, seqid, source, featuretype, start, end, score, strand, frame, attributes, extra,  bin, features.rowid as file_order FROM features          JOIN relations        ON relations.child = features.id        WHERE relations.parent = 'PASA_cluster_100000'          AND features.featuretype = 'transcript';`
Timer of this query outputs 

> Run Time: real 0.151 user 0.140000 sys 0.008000

The QUERY PLAN for this is 

> 0           0           0           SEARCH TABLE features USING INDEX featuretype (featuretype=?)
> 0           1           1           SEARCH TABLE relations USING COVERING INDEX sqlite_autoindex_

Looks like the problem is in selecting FEATURES.ROWID AS FILE_ORDER. If you remove this from the query then the timer goes down to 0.000   : - ))
> Run Time: real 0.000 user 0.000000 sys 0.000000

And the QUERY PLAN in this case is modified 
> 0           0           1           SEARCH TABLE relations USING COVERING INDEX sqlite_autoindex_relations_1 (parent=?)
> 0           1           0           SEARCH TABLE features USING INDEX sqlite_autoindex_features_1 (id=?)               
> 0           0           0           USE TEMP B-TREE FOR DISTINCT  

Now the RELATIONS table is scanned first and THEN FEATURES is scanned. I have no idea why this happens. Since SQLite is declarative we have no real control of what is happening behind the scenes. 
Another possibility to take control of the search order is split this query into to subqueries when first the relations table is searched for children of feature and then they are filtered for requested featuretype.
I also want to mention that without `featuretype` keyword the `children` method  is already fast and with simple python hook including `filter` slow searches can be avoided.

**Comment by pommy1** [comment]
Already optimized in latest version. I was using the old one
