### ISSUE TITLE
My GFF3 file has a fasta sequence at the end

### ISSUE THREAD

**Issue by lfaller** [daler/gffutils#99]
Hi all,

I read in the docs that gffutils doesn't deal with fasta sequences at the end of the gff file (as described here: http://pythonhosted.org/gffutils/examples.html#hybrid1-gff3)

Do you have a recommendation as to how to treat these files?

Specifically, I am trying to write a script that extracts all the fasta sequences for the "CDS"-labeled features.

Is this something I can do with gffutils, or should I write my own parser?

Thanks a bunch!
~Lina

Edited to add: there may be more than one fasta sequence at the end of the file

**Comment by daler** [comment]
Currently there's no support for extracting the sequence from a gff file. In this case you would manually extract the sequence into a separate fasta file. Once you have that, the `Feature.sequence` method will get you the sequence you need. For example:

```python
import gffutils
db = create_db('file.gff', 'file.db')
for feature in db.features_of_type('CDS'):
    seq = feature.sequence('file.fa')
```

If you don't need to do anything fancy with your GFF, you might want to try `bedtools getfasta` using just the CDSs extracted (grep or awk) and the separate fasta file.

**Comment by lfaller** [comment]
Thanks! I split the file into two and processed it as you suggested!
